import { createStore } from "vuex";
import { v4 as uuidv4 } from "uuid";

export default createStore({
  state: {
    level: localStorage.getItem("level"),
    game: JSON.parse(localStorage.getItem("game")),
    loader: true,
    theme: {
      isDark: JSON.parse(localStorage.getItem("isDark")) || false,
    },
    pageLoader: false,
    vocabularyTopic: null,
    vocabularyTopics: [
      {
        title: "Family",
        id: uuidv4(),
        icon: "fa-users",
        route: "/vocabulary-list",
      },
      {
        title: "Animals",
        id: uuidv4(),
        icon: "fa-paw",
        route: "/vocabulary-list",
      },
      {
        title: "Sports",
        id: uuidv4(),
        icon: "fa-volleyball",
        route: "/vocabulary-list",
      },
      {
        title: "Food",
        id: uuidv4(),
        icon: "fa-utensils",
        route: "/vocabulary-list",
      },
      {
        title: "Colors",
        id: uuidv4(),
        icon: "fa-brush",
        route: "/vocabulary-list",
      },
      {
        title: "Jobs",
        id: uuidv4(),
        icon: "fa-user-doctor",
        route: "/vocabulary-list",
      },
      {
        title: "Emotions",
        id: uuidv4(),
        icon: "fa-face-surprise",
        route: "/vocabulary-list",
      },
    ],
    vocabularyData: [
      {
        id: uuidv4(),
        topic: "Family",
        introText: `
          Тема семьи, родственников и родственных связей всегда актуальна, ведь
          это самые близкие люди, которые окружают нас практически всю нашу жизнь.
          Бесспорно, в семье постоянно что-то происходит: кто-то женится, у
          кого-то рождаются дети или внуки, кто-то расстается и т. д. Для того,
          чтобы уметь рассказать о своей семье и родственниках по-английски, очень
          важно иметь необходимый запас английских слов. В данной статье
          представлены самые употребляемые слова и фразы о членах семьи на
          английском, которые помогут вам свободно излагать свои мысли на эту
          тему.
        `,
        introImage: "assets/vocabulary/family.jpg",
        words: [
          {
            en: "family",
            ru: "семья",
          },
          {
            en: "parents",
            ru: "родители",
          },
          {
            en: "son",
            ru: "сын",
          },
          {
            en: "daughter",
            ru: "дочь",
          },
          {
            en: "brother",
            ru: "брат",
          },
          {
            en: "sister",
            ru: "сестра",
          },
          {
            en: "mother",
            ru: "мать",
          },
          {
            en: "father",
            ru: "отец",
          },
          {
            en: "grandparents",
            ru: "дедушка и бабушка",
          },
          {
            en: "grandmother",
            ru: "бабушка",
          },
          {
            en: "grandfather",
            ru: "дедушка",
          },
          {
            en: "grandchildren",
            ru: "внуки",
          },
          {
            en: "grandson",
            ru: "внук",
          },
          {
            en: "granddaughter",
            ru: "внучка",
          },
          {
            en: "aunt",
            ru: "тётя",
          },
          {
            en: "uncle",
            ru: "дядя",
          },
          {
            en: "nephew",
            ru: "племянник",
          },
          {
            en: "niece",
            ru: "племянница",
          },
          {
            en: "cousins",
            ru: "кузены",
          },
          {
            en: "relative",
            ru: "родственник",
          },
          {
            en: "in-law",
            ru: "члены семьи по супругу",
          },
          {
            en: "spouse ",
            ru: "супруг ",
          },
          {
            en: "stepmother / Stepfather",
            ru: "мачеха / отчим",
          },
          {
            en: "stepsister / stepbrother",
            ru: "сводня сестра / сводный брат",
          },
          {
            en: "half-sister",
            ru: "сестра по одному из родителей",
          },
          {
            en: "half-brother",
            ru: "брат по одному из родителей",
          },
          {
            en: "godparents",
            ru: "крестные родители",
          },
          {
            en: "godfather",
            ru: "крестный",
          },
          {
            en: "godmother",
            ru: "крестная",
          },
          {
            en: "godson",
            ru: "крестник",
          },
          {
            en: "goddaughter",
            ru: "крестница",
          },
          {
            en: "bridegroom",
            ru: "жених",
          },
          {
            en: "husband",
            ru: "муж",
          },
          {
            en: "bride",
            ru: "невеста",
          },
          {
            en: "wife",
            ru: "жена",
          },
          {
            en: "single",
            ru: "холостой",
          },
          {
            en: "widow",
            ru: "вдова",
          },
          {
            en: "widower",
            ru: "вдовец",
          },
          {
            en: "triplets",
            ru: "тройняшки",
          },
          {
            en: "twins",
            ru: "близнецы",
          },
        ],
      },
      {
        id: uuidv4(),
        topic: "Animals",
        introText: `
          Все мы в какой–то степени зависим от братьев наших меньших.
          Эти милые комочки счастья приносят нам радость и поднимают настроение.
          И хотя не всех животных можно назвать милыми,
          от этого их роль в существовании на планете Земля не менее важна.
          Названия животных в английском языке (лесные, травоядные, млекоплитающие, африканские и другие)
          входят в базовый словарь, который проходят все студенты при изучении английского языка.
          Чтобы ваш словарный запас не заканчивался на собачках и кошечках нужно приложить немного усилий. C'mon!
        `,
        introImage: "assets/vocabulary/animals.jpg",
        words: [
          {
            en: "сat",
            ru: "кот",
          },
          {
            en: "kitten",
            ru: "котенок",
          },
          {
            en: "dog",
            ru: "собака",
          },
          {
            en: "puppy",
            ru: "щенок",
          },
          {
            en: "hamster",
            ru: "хомяк",
          },
          {
            en: "parrot",
            ru: "попугай",
          },
          {
            en: "guinea pig",
            ru: "морская свинка",
          },
          {
            en: "crocodile",
            ru: "крокодил",
          },
          {
            en: "deer",
            ru: "олень",
          },
          {
            en: "elephant",
            ru: "слон",
          },
          {
            en: "elk",
            ru: "лось",
          },
          {
            en: "fox",
            ru: "лиса",
          },
          {
            en: "giraffe",
            ru: "жираф",
          },
          {
            en: "goat",
            ru: "козёл",
          },
          {
            en: "hare",
            ru: "заяц",
          },
          {
            en: "unchippopotamus",
            ru: "бегемот",
          },
          {
            en: "hyena",
            ru: "гиена",
          },
          {
            en: "jaguar",
            ru: "ягуар",
          },
          {
            en: "leopard",
            ru: "леопард",
          },
          {
            en: "lion",
            ru: "лев",
          },
          {
            en: "lynx",
            ru: "рысь",
          },
          {
            en: "marten",
            ru: "куница",
          },
          {
            en: "mink",
            ru: "норка",
          },
          {
            en: "mongoose",
            ru: "мангуст",
          },
          {
            en: "monkey",
            ru: "мартышка",
          },
          {
            en: "mouse",
            ru: "мышь",
          },
          {
            en: "hedgehog",
            ru: "еж",
          },
          {
            en: "muskrat",
            ru: "ондатра",
          },
          {
            en: "otter",
            ru: "выдра",
          },
          {
            en: "panda",
            ru: "панда",
          },
          {
            en: "panther",
            ru: "пантера",
          },
          {
            en: "polar",
            ru: "песец",
          },
          {
            en: "puma",
            ru: "пума",
          },
          {
            en: "raccoon",
            ru: "енот",
          },
          {
            en: "rhinoceros",
            ru: "носорог",
          },
          {
            en: "sable",
            ru: "соболь",
          },
          {
            en: "squirrel",
            ru: "белка",
          },
          {
            en: "tiger",
            ru: "тигр",
          },
          {
            en: "yak",
            ru: "як",
          },
          {
            en: "wolf",
            ru: "волк",
          },
        ],
      },
      {
        id: uuidv4(),
        topic: "Sports",
        introText: `
          До определенного момента вы можете просто заниматься спортом, не зная ни слова по-английски.
          Ходить к тренеру в своем городе, заниматься в группе, оттачивать свои навыки. Может, просто как хобби
          или для поддержания тонуса. Но если вы захотите идти дальше, тут уже без английского никак.
          Представьте себе ситуацию. Вы победили на чемпионате в родной стране, и вот вас отправили на международный турнир.
          Вы прилетаете, например, в Великобританию. Пропустим тот момент, что вам понадобится английский в аэропорту или хотя бы
          элементарные знания английского в ресторане. Допустим, у вашей команды есть переводчик или тренер с хорошим знанием языка.
          Вы кое как всей группой заселяетесь в отель, выступаете наконец на чемпионате и (О да!) становитесь победителем.
          Вас показывают по всем спортивным телеканалам в прямом эфире, десятки спортивных журналистов выстраиваются в очередь, чтобы взять
          ваш комментарий. Одна проворная журналистка с Eurosport подбегает к вам с микрофоном, что-то бормочет на английском языке, а вы 
          даже не можете ей ответить. И вот уже эйфория от победы разбавляется неловкостью из-за ситуации, где чемпион мира даже не знает английского языка.
        `,
        introImage: "assets/vocabulary/sports.jpg",
        words: [
          {
            en: "champion",
            ru: "чемпион",
          },
          {
            en: "championship",
            ru: "соревнование",
          },
          {
            en: "game",
            ru: "игра",
          },
          {
            en: "tournament",
            ru: "турнир",
          },
          {
            en: "team",
            ru: "команда",
          },
          {
            en: "result",
            ru: "результат",
          },
          {
            en: "victory",
            ru: "победа",
          },
          {
            en: "defeat",
            ru: "поражение",
          },
          {
            en: "draw",
            ru: "ничья",
          },
          {
            en: "record",
            ru: "рекорд",
          },
          {
            en: "medal",
            ru: "медаль",
          },
          {
            en: "field",
            ru: "поле",
          },
          {
            en: "net",
            ru: "сетка",
          },
          {
            en: "football",
            ru: "футбол",
          },
          {
            en: "basketball",
            ru: "баскетбол",
          },
          {
            en: "volleyball",
            ru: "волейбол",
          },
          {
            en: "boxing",
            ru: "бокс",
          },
          {
            en: "golf",
            ru: "гольф",
          },
          {
            en: "player",
            ru: "игрок",
          },
          {
            en: "referee",
            ru: "судья",
          },
          {
            en: "dummy",
            ru: "финт",
          },
          {
            en: "whistle",
            ru: "свисток",
          },
          {
            en: "check",
            ru: "шах",
          },
          {
            en: "checkmate",
            ru: "мат",
          },
          {
            en: "giveup",
            ru: "сдаться",
          },
          {
            en: "hole",
            ru: "лунка",
          },
          {
            en: "Birdie",
            ru: "берди",
          },
          {
            en: "Shank",
            ru: "шенк",
          },
          {
            en: "Putt",
            ru: "патт",
          },
          {
            en: "Fore",
            ru: "фо",
          },
          {
            en: "Chip",
            ru: "чип",
          },
          {
            en: "backboard",
            ru: "щит",
          },
          {
            en: "basket",
            ru: "кольцо",
          },
          {
            en: "gloves",
            ru: "перчатки",
          },
          {
            en: "states",
            ru: "коньки",
          },
          {
            en: "blade",
            ru: "лезвие коньков",
          },
          {
            en: "hockey stick",
            ru: "клюшка",
          },
          {
            en: "pivot",
            ru: " ключевой игрок",
          },
          {
            en: "defender",
            ru: "защитник",
          },
          {
            en: "attacker",
            ru: "нападающий",
          },
        ],
      },
      {
        id: uuidv4(),
        topic: "Food",
        introText: `
        Всем привет. Мы вдруг обнаружили, что у нас в блоге до их пор не было полноценной подборки фруктов, овощей и ягод.
        Пришло время это исправить. Иначе как же вы будете ходить в супермаркет или готовить, даже не зная, как будет на английском «клюква» или «слива».
        Окей. Сегодняшнюю подборку мы разбили на несколько блоков. Начнем же наконец!
        `,
        introImage: "assets/vocabulary/food.webp",
        words: [
          {
            en: "a sandwich",
            ru: "бутерброд",
          },
          {
            en: "toast",
            ru: "поджаренный хлеб",
          },
          {
            en: "a cake",
            ru: "торт",
          },
          {
            en: "a bun",
            ru: "булочка",
          },
          {
            en: "tea",
            ru: "чай",
          },
          {
            en: "coffee",
            ru: "кофе",
          },
          {
            en: "sugar",
            ru: "сахар",
          },
          {
            en: "porridge",
            ru: "каша",
          },
          {
            en: "cheese",
            ru: "сыр",
          },
          {
            en: "sausage",
            ru: "колбаса",
          },
          {
            en: "salt",
            ru: "соль",
          },
          {
            en: "pepper",
            ru: "перец",
          },
          {
            en: "salad",
            ru: "салат",
          },
          {
            en: "soup",
            ru: "суп",
          },
          {
            en: "meat",
            ru: "мясо",
          },
          {
            en: "chiсken",
            ru: "курица",
          },
          {
            en: "fish",
            ru: "рыба",
          },
          {
            en: "cutlets",
            ru: "котлеты",
          },
          {
            en: "potatoes",
            ru: "картошка",
          },
          {
            en: "tomatoes",
            ru: "помидоры",
          },
          {
            en: "vegetables",
            ru: "овощи",
          },
          {
            en: "butter",
            ru: "масло",
          },
          {
            en: "milk",
            ru: "молоко",
          },
          {
            en: "juice",
            ru: "сок",
          },
          {
            en: "fruit",
            ru: "фрукты",
          },
          {
            en: "Spinach",
            ru: "Шпинат",
          },
          {
            en: "Squash",
            ru: "Кабачок",
          },
          {
            en: "Turnip",
            ru: "Репа",
          },
          {
            en: "Nut",
            ru: "Орех",
          },
          {
            en: "Papaya",
            ru: "Папайя",
          },
          {
            en: "Raspberry",
            ru: "Малина",
          },
          {
            en: "Strawberry",
            ru: "Клубника",
          },
          {
            en: "Cherry",
            ru: "Вишня",
          },
          {
            en: "Coconut",
            ru: "Кокос",
          },
          {
            en: "Mango",
            ru: "Манго",
          },
          {
            en: "Raisin",
            ru: "Изюм",
          },
          {
            en: "Ripe",
            ru: "Зрелый",
          },
          {
            en: "Rotten",
            ru: "Гнилой",
          },
          {
            en: "Apricot",
            ru: "Абрикос",
          },
          {
            en: "Plum",
            ru: "Слива",
          },
        ],
      },
      {
        id: uuidv4(),
        topic: "Colors",
        introText: `
        Цвета в нашей жизни имеют огромное значение. Просто представьте свою жизнь без них на один день — окружающий мир станет серым и неинтересным — и вы увидите,
        насколько сильно мы нуждаемся в них. При помощи цветов даже определяют стороны характера и качества личности в психологии! Что же касается английского, то так же,
        как и во всех языках мира, цвета используются повсеместно для описания предметов, их состояния; людей и их внешности, окружающей обстановки и так далее.
        Давайте же посмотрим на основные нюансы употребления цветов в английском языке, а также остановимся и запомним некоторые интересные исключения и идиомы связанные с ними.
        Начнем, пожалуй, с самых основ. С самого слова «цвет» в английском.
        `,
        introImage: "assets/vocabulary/colors.jpg",
        words: [
          {
            en: "Red",
            ru: "красный",
          },
          {
            en: "Grey",
            ru: "серый",
          },
          {
            en: "Light blue",
            ru: "голубой ",
          },
          {
            en: "Dark blue",
            ru: "синий",
          },
          {
            en: "Green",
            ru: "зеленый",
          },
          {
            en: "Yellow",
            ru: "желтый",
          },
          {
            en: "Pink",
            ru: "розовый",
          },
          {
            en: "Orange",
            ru: "оранжевый",
          },
          {
            en: "Brown",
            ru: "коричневый",
          },
          {
            en: "White",
            ru: "белый",
          },
          {
            en: "Black",
            ru: "черный",
          },
          {
            en: "Violet",
            ru: "фиолетовый",
          },
          {
            en: "Gold",
            ru: "золотой",
          },
          {
            en: "Silver",
            ru: "серебряный",
          },
          {
            en: "Amber ",
            ru: "янтарный",
          },
          {
            en: "Azure",
            ru: "голубой",
          },
          {
            en: "Beige",
            ru: "бежевый",
          },
          {
            en: "Body colour",
            ru: "телесный цвет",
          },
          {
            en: "Bronze",
            ru: "бронзовый",
          },
          {
            en: "Chocolate",
            ru: "шоколадный",
          },
          {
            en: "Coral",
            ru: "коралловый",
          },
          {
            en: "Denim blue",
            ru: "джинсовый",
          },
          {
            en: "Lilac",
            ru: "сиреневый",
          },
          {
            en: "Pearl",
            ru: "жемчужный",
          },
          {
            en: "Raspberry",
            ru: "малиновый",
          },
          {
            en: "Sand",
            ru: "песочный",
          },
          {
            en: "Snow",
            ru: "белоснежный",
          },
          {
            en: "Vinous",
            ru: "бордовый",
          },
          {
            en: "Light sea green",
            ru: " цвет морской волны",
          },
          {
            en: "Turquoise",
            ru: "бирюзовый",
          },
          {
            en: "Emerald",
            ru: "изумрудный",
          },
          {
            en: "olive",
            ru: "оливковый",
          },
          {
            en: "plum",
            ru: "сливовый",
          },
          {
            en: "lavender",
            ru: "бледно-лиловый",
          },
          {
            en: "ivory",
            ru: "цвет слоновой кости",
          },
          {
            en: "salmon",
            ru: "оранжево-розовый",
          },
          {
            en: "maroon",
            ru: "темно-бордовый",
          },
          {
            en: "сhocolate",
            ru: "шоколадный ",
          },
          {
            en: "darkgreen",
            ru: "темно-зелёный",
          },
          {
            en: "darkred",
            ru: "темно-красный",
          },
        ],
      },
      {
        id: uuidv4(),
        topic: "Jobs",
        introText: `
          Чтобы свободно называть основные профессии на английском, нужно выучить всю необходимую лексику. Для этого мы подготовили для вас глоссарий и составили таблички со списками профессий.
          Профессии разделены по тематикам, чтобы легче в них ориентироваться. Сохраняйте таблицы и учите новые слова.
          Профессии из этого списка чаще других можно встретить в учебниках английского языка и в реальных диалогах.
          Лучше сразу их запомнить, чтобы без труда выполнять разные задания на уроках английского.
        `,
        introImage: "assets/vocabulary/jobs-man.png",
        words: [
          {
            en: "Engineer",
            ru: "Инженер",
          },
          {
            en: "Sportsman ",
            ru: "Спортсмен",
          },
          {
            en: "Cook",
            ru: "Повар ",
          },
          {
            en: "Policeman",
            ru: "Полицейский",
          },
          {
            en: "Lawyer ",
            ru: "Юрист",
          },
          {
            en: "Journalist ",
            ru: "Журналист",
          },
          {
            en: "Driver  ",
            ru: "Водитель",
          },
          {
            en: "Businessman ",
            ru: "Бизнесмен",
          },
          {
            en: "Doctor ",
            ru: "Врач",
          },
          {
            en: "Actor ",
            ru: "Актер",
          },
          {
            en: "Teacher ",
            ru: "Учитель",
          },
          {
            en: "Housewife ",
            ru: "Домохозяйка",
          },
          {
            en: "Cosmonaut ",
            ru: "Космонавт",
          },
          {
            en: "Builder ",
            ru: "Строитель",
          },
          {
            en: "Seller ",
            ru: "Продавец",
          },
          {
            en: "Fireman ",
            ru: "Пожарный",
          },
          {
            en: "Postman ",
            ru: "Почтальон",
          },
          {
            en: "Veterinarian",
            ru: "Ветеринар",
          },
          {
            en: "Artist ",
            ru: "Художник",
          },
          {
            en: "Writer ",
            ru: "Писатель",
          },
          {
            en: "Musician",
            ru: "Музыкант",
          },
          {
            en: "Actress",
            ru: "Актриса",
          },
          {
            en: "Makeup artist ",
            ru: "Визажист",
          },
          {
            en: "Designer ",
            ru: "Дизайнер",
          },
          {
            en: "DJ ",
            ru: "Диджей",
          },
          {
            en: "Sound Producer ",
            ru: "Звукорежиссер",
          },
          {
            en: "Beatmaker",
            ru: "Битмейкер",
          },
          {
            en: "Director ",
            ru: "Режиссер",
          },
          {
            en: "Cameraman",
            ru: "Оператор",
          },
          {
            en: "Composer ",
            ru: "Композитор ",
          },
          {
            en: "Model ",
            ru: "Модель ",
          },
          {
            en: "Interpreter  ",
            ru: "Переводчик ",
          },
          {
            en: "Producer ",
            ru: "Продюсер ",
          },
          {
            en: "Stylist ",
            ru: "Стилист",
          },
          {
            en: "Photographer",
            ru: "Фотограф",
          },
          {
            en: "Jeweller ",
            ru: "Ювелир",
          },
          {
            en: "Editor ",
            ru: "Редактор",
          },
          {
            en: "Screenwriter ",
            ru: "Сценарист ",
          },
          {
            en: "Poet",
            ru: "Поэт",
          },
          {
            en: "Sculptor",
            ru: "Скульптор",
          },
        ],
      },
      {
        id: uuidv4(),
        topic: "Emotions",
        introText: `
          Сегодня мы дадим вам лексику на тему эмоций. На момент публикации это самая исчерпывающая подборка в интернете.
          Мы проверили. Даже если у вас высокий уровень, вы наверняка найдете здесь для себя новые слова.
        `,
        introImage: "assets/vocabulary/emotions.jpg",
        words: [
          {
            en: "Angry",
            ru: "злой",
          },
          {
            en: "Annoyed",
            ru: "раздраженный",
          },
          {
            en: "Bored",
            ru: "скучающий",
          },
          {
            en: "Calm",
            ru: "спокойный",
          },
          {
            en: "Careful",
            ru: "заботливый",
          },
          {
            en: "Confused",
            ru: "недоумевающий",
          },
          {
            en: "Confident",
            ru: "уверенный",
          },
          {
            en: "Dangerous",
            ru: "опасный",
          },
          {
            en: "Depressed",
            ru: "подавленный",
          },
          {
            en: "Disappointed",
            ru: "расстроенный",
          },
          {
            en: "Distant",
            ru: "отстраненный",
          },
          {
            en: "Dreamy",
            ru: "мечтательный",
          },
          {
            en: "Empty",
            ru: "опустошенный",
          },
          {
            en: "Energetic",
            ru: "энергичный",
          },
          {
            en: "Excited",
            ru: "взволнованный",
          },
          {
            en: "Happy",
            ru: "счастливый ",
          },
          {
            en: "Hungry",
            ru: "голодный ",
          },
          {
            en: "Hostile",
            ru: "враждебный",
          },
          {
            en: "Interested",
            ru: "заинтересованный",
          },
          {
            en: "Isolated",
            ru: "изолированный",
          },
          {
            en: "Joyful",
            ru: "радостный",
          },
          {
            en: "Lovely",
            ru: "прекрасный",
          },
          {
            en: "Lucky",
            ru: "везучий",
          },
          {
            en: "Mad",
            ru: "безумный",
          },
          {
            en: "Peaceful",
            ru: "умиротворенный",
          },
          {
            en: "Optimistic",
            ru: "оптимистично-настроенный",
          },
          {
            en: "Pleased",
            ru: "довольный",
          },
          {
            en: "Powerless",
            ru: " лишенный сил",
          },
          {
            en: "Sad",
            ru: "грустный",
          },
          {
            en: "Shocked",
            ru: "шокированный",
          },
          {
            en: "Shy",
            ru: "стеснительный",
          },
          {
            en: "Proud",
            ru: "гордый",
          },
          {
            en: "Scared",
            ru: "испуганный",
          },
          {
            en: "Sleepy",
            ru: "сонный",
          },
          {
            en: "Sorrowful",
            ru: "опечаленный",
          },
          {
            en: "Tired",
            ru: "уставший",
          },
          {
            en: "Unpleasant",
            ru: "неприятный",
          },
          {
            en: "Thoughtful",
            ru: "задумавшийся",
          },
          {
            en: "Worried",
            ru: "тревожный",
          },
          {
            en: "Sorry",
            ru: "огорченный",
          },
        ],
      },
    ],
    testTopic: null,
    testTopics: [
      {
        title: "Present Simple",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Present Perfect",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Present Continious",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Past Simple",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },

      {
        title: "Past Perfect",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Past Continious",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Infinitive & Gerund",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Family in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Animals in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Colors in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Jobs in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Sports in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Food in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
      {
        title: "Emotions in English",
        id: uuidv4(),
        icon: "",
        route: "/test-list",
      },
    ],
    testData: [
      {
        topic: "Present Simple",
        questions: [
          "I ____ tea.",
          "She ____ two brothers.",
          "Tom ____ work until 10 today.",
          "____ an instrument?",
          "The museum ___ at 10 o'clock.",
          "Peter and Megan often ____ to the cinema.",
          "John ____ very late.",
          "What time ___ home in the morning?",
          "What language ____ ?",
          "My son never ____ cartoons.",
        ],
        options: [
          ["not drink", "don't drink", "drink not"],
          ["have", "has", "haves"],
          ["doesn't starts", "doesn't start", "do not start"],
          ["You do play", "do you play", "you play"],
          ["open", "does open", "opens"],
          ["do go", "go", "goes"],
          ["doesn't get up", "do not get up", "doesn't gets up"],
          ["do they leave", "they do leave", "they leave"],
          ["do he studies", "does he studies", "does he study"],
          ["watchs", "watch", "watches"],
        ],
        answers: [
          "don't drink",
          "has",
          "doesn't start",
          "do you play",
          "opens",
          "go",
          "doesn't get up",
          "do they leave",
          "does he study",
          "watches",
        ],
        id: uuidv4(),
      },
      {
        topic: "Present Perfect",
        questions: [
          "He ___ his work. Why don’t we invite him out?",
          "Tom and I ___ friends since childhood.",
          "She ___ a job so far.",
          "The students ___ their essays.",
          "Nick ___ a live football match before.",
          "___ yet?",
          "Lisa and Frank ___ married for two years now.",
          "I ___ part in marathons.",
          "He ___ his cottage yet.",
          "My wife ___ invitations for the party.",
        ],
        options: [
          ["have finished", "has finished", "has finish"],
          ["were been", "has been", "have been"],
          ["not has found", "haven’t found", "hasn’t found"],
          ["has just completed", "have just completed", "have just complete"],
          ["has never seen", "hasn’t never seen", "have never seen"],
          [
            "Have the rain stopped",
            "Has the rain stop",
            "Has the rain stopped",
          ],
          ["have were", "has been", "have been"],
          ["has never taken", "have never taken", "haven’t never taken"],
          ["hasn’t sold", "not has sold", "haven’t sold"],
          ["has already send", "has already sent", "have already sent"],
        ],
        answers: [
          "has finished",
          "have been",
          "hasn’t found",
          "have just completed",
          "has never seen",
          "Has the rain stopped",
          "have been",
          "have never taken",
          "hasn’t sold",
          "has already sent",
        ],
        id: uuidv4(),
      },
      {
        topic: "Present Continious",
        questions: [
          "Ron and Michael ___ at the table and doing their homework.",
          "He ___ how to use a computer at the moment.",
          "I ___ to find a place to stay at the moment.",
          "Both my friend and I ___ today.",
          "Look! It ___ any more.",
          "The population of the country ____.",
          "___ in the park right now?",
          "We ___ four eggs to bake this cake.",
          "My brother ___ his own website. It looks great!",
          "My car is broken, so I ___ my mum’s.",
        ],
        options: [
          ["are sitting", "are siting", "is sitting"],
          ["is learning", "is learn", "are learning"],
          ["am try", "am trying", "trying"],
          ["are working", "am working", "is working"],
          ["is raining", "isn’t raining", "aren’t raining"],
          [
            "is constantly increasing",
            "is constantly increase",
            "are constantly increasing",
          ],
          ["Is she running", "Is she run", " Is she runing"],
          ["are need", "are needing", "need"],
          ["designing", "is designing", "are designing"],
          ["is using", "am using", "am use"],
        ],
        answers: [
          "are sitting",
          "is learning",
          "am trying",
          "are working",
          "isn’t raining",
          "is constantly increasing",
          "Is she running",
          "need",
          "is designing",
          "am using",
        ],
        id: uuidv4(),
      },
      {
        topic: "Past Simple",
        questions: [
          "Who ___ the first airplane?",
          "Sandra ___ her English exam successfully yesterday.",
          "___ a new TV program yesterday?",
          "We ___ to sell our old house and buy a new one.",
          "She ___ French when she was at school.",
          "It was my brother’s birthday on Sunday, so I ___ him a postcard.",
          "How much time ___ in Germany last month?",
          "When ___ your new garage?",
          "My uncle ___ a yacht last week.",
          "My dad ___ when he was little.",
        ],
        options: [
          ["did invented", "did invent", "invented"],
          ["passed", "pased", "did pass"],
          ["Watched you", "Did you watch", "Did you watched"],
          ["decided", "did decided", "did decide"],
          ["study", "did study", "studied"],
          ["sent", "send", "sended"],
          ["did you spended", "did you spend", "did you spent"],
          ["did you build", "did you built", "you built"],
          ["bought", "buyed", "did buy"],
          ["didn’t smoked", "not smoked", "didn’t smoke"],
        ],
        answers: [
          "invented",
          "passed",
          "Did you watch",
          "decided",
          "studied",
          "sent",
          "did you spend",
          "did you build",
          "bought",
          "didn’t smoke",
        ],
        id: uuidv4(),
      },
      {
        topic: "Past Perfect",
        questions: [
          "There were puddles in the streets as it ___ all night.",
          "Mom was tired yesterday. She ___ the house all day.",
          "When we came back home, the children ___ for two hours.",
          "My mom ___ dinner when I returned home.",
          "Mark told me that he ___ a new suit.",
          "Andrew said he___ to China before.",
          "Jack said he ___ tickets for the concert.",
          "Claire said she ___ her sister since last month.",
          "Tina ___ home when I phoned her.",
          "I ___ for an hour before it got dark.",
        ],
        options: [
          ["had raining", "had been raining", "had rained"],
          ["had cleaned", "had been cleaning", "had been cleaned"],
          [
            "had already been sleeping",
            "had already slept",
            "had already be sleeping",
          ],
          ["had already cooked", "had already been", "had already cooking"],
          ["had being bought", "had been buying", "had bought"],
          ["had never been", "had never being", "hadn’t never been"],
          ["had booked", "had been booked", "had been booking"],
          ["hadn’t phoned", "hadn’t phoning", "not had phoned"],
          ["had just been getting", "had just get", "had just got buy"],
          ["had been walking", "had walked", "had walking"],
        ],
        answers: [
          "had been raining",
          "had been cleaning",
          "had already been sleeping",
          "had already cooked",
          "had bought",
          "had never been",
          "had booked",
          "hadn’t phoned",
          "had just got",
          "had been walking",
        ],
        id: uuidv4(),
      },
      {
        topic: "Past Continious",
        questions: [
          "They ___ cricket at 10 a.m. yesterday.",
          "We ___ tea when our grandparents came.",
          "I ___ anything this time yesterday.",
          "___ at 8 p.m. yesterday?",
          "She ___ dinner while her husband was working in the garden.",
          "Why ___ at you?",
          "The radio was on but nobody ___ to it.",
          "Tom and Liz were busy yesterday. They ___ their mom around the house.",
          "He ___ the house this time yesterday.",
          "When I got home, my sister ___ with a kitten.",
        ],
        options: [
          ["not playing", "weren’t playing", "wasn’t playing"],
          ["was having", "were have", "were having"],
          ["wasn’t doing", " weren’t doing", " not doing"],
          ["Knitting she", "Were she knitting", "Was she knitting"],
          ["were cooking", "was cooking", "was cook"],
          [
            "were that woman staring",
            "was that woman staring",
            "was that woman stare",
          ],
          ["weren’t listening", "was listening", "were listening"],
          ["was helping", "were helping", "helping"],
          ["was painting", "were painting", "painting"],
          ["playing", "was playing", "were playing"],
        ],
        answers: [
          "weren’t playing",
          "were having",
          "wasn’t doing",
          "Was she knitting",
          "was cooking",
          "was that woman staring",
          "was listening",
          "were helping",
          "was painting",
          "was playing",
        ],
        id: uuidv4(),
      },
      {
        topic: "Infinitive & Gerund",
        questions: [
          "I prefer ___ outdoor games.",
          "Mike warned his sister not ___ back late.",
          "All children enjoy ___ sweets.",
          "Mark insists on ___ a picnic this Sunday.",
          "Ann didn’t know what ___.",
          "I can remember ___ into the river when I was ten.",
          "We arranged ___ back home on 10 June.",
          "Andrew hates ___ early in the morning.",
          "Ken failed ___ new friends at school.",
          "What are you going to do after ___ school?",
        ],
        options: [
          ["playing", "to playing", "to play"],
          ["to coming", "to come", "come"],
          ["eating", "to eating", "to eat"],
          ["having", "have", "to having"],
          ["to answer", "answering", "answer"],
          ["fall", "falling", "to fall"],
          ["to return", "returning", " return"],
          ["to getting up", "to get up", "getting up"],
          ["to making", "making", "to make"],
          ["finishing", "to finish", "to finishing"],
        ],
        answers: [
          "playing",
          "to come",
          "eating",
          "having",
          "to answer",
          "falling",
          "to return",
          "to get up",
          "to make",
          "finishing",
        ],
        id: uuidv4(),
      },
      {
        topic: "Family in English",
        questions: [
          "Семья",
          "Родители",
          "Сын",
          "Дочь",
          "Брат",
          "Сестра",
          "Мать",
          "Отец",
          "Дедушка и бабушка",
          "Бабушка",
          "Внуки",
          "Дядя",
          "Тетя",
          "Племянник",
          "Племянница",
          "Кузены",
          "Родственники",
          "Со стороны супруга",
          "Супруг",
          "Мачеха",
          "Отчим",
          "Сводная сестра",
          "Сводный брат",
          "Брат по одному родителю",
          "Сестра по одному родителю",
          "Жених",
          "Невеста",
          "Вдова",
          "Вдовец",
        ],
        options: [
          ["NIECE", "FAMILY", "WIFE", "BRIDEGROOM"],
          ["PARENTS", "SPOUSE", "GRANDMOTHER", "BROTHER"],
          ["DAUGHTER", "SON", "BRIDEGROOM", "SISTER"],
          ["FATHER", "DAUGHTER", "NEPHEW", "BRIDEGROOM"],
          ["WIDOWER", "AUNT", "SON", "BROTHER"],
          ["UNCLE", "NIECE", "SISTER", "MOTHER"],
          ["FAMILY", "MOTHER", " PARENTS", "STEP MOM"],
          ["UNCLE", "FATHER", "STEP FATHER", "FAMILY"],
          ["MOTHER", "GRANDPARENTS", "GRANDCHILDREN", "PARENTS"],
          ["GRANDMOTHER", "HALF-SISTER", "HALF-BROTHER", "BRIDEGROOM"],
          ["GRANDCHILDREN", "AUNT", "SON", "RELATIVES"],
          ["AUNT", "UNCLE", "SON", "COUSINS"],
          ["SISTER", "WIDOWER", "GRANDPARENTS", "NEPHEW"],
          ["SPOUSE", "AUNT", "SON", "NIECE"],
          ["GRANDMOTHER", "COUSINS", "STEP FATHER", "PARENTS"],
          ["GRANDPARENTS", "GRANDCHILDREN", "RELATIVES", "FAMILY"],
          ["UNCLE", "IN-LAW", "STEP MOM", "STEP FATHER"],
          ["IN-LAW", "SPOUSE", "COUSINS", "HALF-SISTER"],
          ["STEP MOM", "WIDOWER", "GRANDMOTHER", "NEPHEW"],
          ["NIECE", "FAMILY", "WIFE", "STEP FATHER"],
          ["PARENTS", "SPOUSE", "AUNT", "BROTHER"],
          ["DAUGHTER", "STEP SISTER", "BRIDEGROOM", "SISTER"],
          ["FATHER", "DAUGHTER", "NEPHEW", "STEP BROTHER"],
          ["HALF-BROTHER", "AUNT", "SON", "PARENTS"],
          ["UNCLE", "HALF-SISTER", "BROTHER", "MOTHER"],
          ["FAMILY", "MOTHER", " COUSINS", "BRIDEGROOM"],
          ["UNCLE", "WIFE", "STEP FATHER", "FAMILY"],
          ["MOTHER", "IN-LAW", "WIDOW", "PARENTS"],
          ["NIECE", "WIDOW", "WIDOWER", "UNCLE"],
        ],
        answers: [
          "FAMILY",
          "PARENTS",
          "SON",
          "DAUGHTER",
          "BROTHER",
          "SISTER",
          "MOTHER",
          "FATHER",
          "GRANDPARENTS",
          "GRANDMOTHER",
          "GRANDCHILDREN",
          "AUNT",
          "UNCLE",
          "NEPHEW",
          "NIECE",
          "COUSINS",
          "RELATIVES",
          "IN-LAW",
          "SPOUSE",
          "STEP MOM",
          "STEP FATHER",
          "STEP SISTER",
          "STEP BROTHER",
          "HALF-BROTHER",
          "HALF-SISTER",
          "BRIDEGROOM",
          "WIFE",
          "WIDOW",
          "WIDOWER",
        ],
        id: uuidv4(),
      },
      {
        topic: "Animals in English",
        questions: [
          "Кот",
          "Котенок",
          "Собака",
          "Щенок",
          "Хомяк",
          "Попугай",
          "Морская свинка",
          "Крокодил",
          "Олень",
          "Слон",
          "Лось",
          "Лиса",
          "Жираф",
          "Козёл",
          "Заяц",
          "Бегемот",
          "Гиена",
          "Ягуар",
          "Леопард",
          "Лев",
          "Рысь",
          "Куница",
          "Норка",
          "Мангуст",
          "Мартышка",
          "Мышь",
          "Еж",
          "Ондатра",
          "Выдра",
        ],
        options: [
          ["сat", "crocodile", "dog", "kitten"],
          ["hamster", "kitten", "parrot", "otter"],
          ["mongoose", "hyena", "dog", "lion"],
          ["giraffe", "jaguar", "guinea pig", "puppy"],
          ["hamster", "otter", "hedgehog", "mouse"],
          ["goat", "parrot", "deer", "сat"],
          ["elephant", "hare", "guinea pig", "muskrat"],
          ["leopard", "parrot", "lynx", "crocodile"],
          ["deer", "monkey", "goat", "hare"],
          ["mongoose", "elephant", "unchippopotamus", "fox"],
          ["giraffe", "jaguar", "elk", "lion"],
          ["goat", "hamster", "hare", "fox"],
          ["giraffe", "dog", "monkey", "otter"],
          ["muskrat", "goat", "marten", "elk"],
          ["deer", "kitten", "hare", "puppy"],
          ["giraffe", "parrot", "leopard", "unchippopotamus"],
          ["hyena", "elk", "hamster", "kitten"],
          ["deer", "jaguar", "kitten", "hamster"],
          ["muskrat", "puppy", "leopard", "deer"],
          ["elk", "elephant", "dog", "lion"],
          ["lynx", "parrot", "guinea pig", "deer"],
          ["puppy", "marten", "elephant", "crocodile"],
          ["hyena", "fox", "mink", "mongoose"],
          ["mink", "lynx", "hedgehog", "mongoose"],
          ["monkey", "hedgehog", "unchippopotamus", "marten"],
          ["crocodile", "mouse", "monkey", "leopard"],
          ["mink", "fox", "hedgehog", "unchippopotamus"],
          ["hyena", "lynx", "crocodile", "muskrat"],
          ["otter", "puppy", "guinea pig", "leopard"],
        ],
        answers: [
          "сat",
          "kitten",
          "dog",
          "puppy",
          "hamster",
          "parrot",
          "guinea pig",
          "crocodile",
          "deer",
          "elephant",
          "elk",
          "fox",
          "giraffe",
          "goat",
          "hare",
          "unchippopotamus",
          "hyena",
          "jaguar",
          "leopard",
          "lion",
          "lynx",
          "marten",
          "mink",
          "mongoose",
          "monkey",
          "mouse",
          "hedgehog",
          "muskrat",
          "otter",
        ],
        id: uuidv4(),
      },
      {
        topic: "Food in English",
        questions: [
          "бутерброд",
          "поджаренный хлеб",
          "торт",
          "булочка",
          "чай",
          "кофе",
          "сахар",
          "каша",
          "сыр",
          "колбаса",
          "соль",
          "перец",
          "салат",
          "суп",
          "мясо",
          "курица",
          "рыба",
          "котлеты",
          "картошка",
          "помидоры",
          "овощи",
          "масло",
          "молоко",
          "сок",
          "фрукты",
          "Шпинат",
          "Кабачок",
          "Репа",
          "Орех",
        ],
        options: [
          ["a sandwich", "coffee", "a bun", "sugar"],
          ["toast", "coffee", "a bun", "sugar"],
          ["porridge", "a cake", "tea", "pepper"],
          ["meat", "milk", "a cake", "a bun"],
          ["tea", "potatoes", "juice", "Spinach"],
          ["salad", "coffee", "vegetables", "sugar"],
          ["fish", "pepper", "sugar", "butter"],
          ["Nut", "Turnip", "soup", "porridge"],
          ["cheese", "salt", "fruit", "vegetables"],
          ["Squash", "sausage", "tomatoes", "toast"],
          ["potatoes", "a cake", "salt", "juice"],
          ["Turnip", "a sandwich", "a bun", "pepper"],
          ["salad", "chiсken", "fish", "cutlets"],
          ["milk", "soup", "Turnip", "sugar"],
          ["cheese", "cutlets", "meat", "Squash"],
          ["a sandwich", "fruit", "vegetables", "chiсken"],
          ["fish", "Nut", "potatoes", "porridge"],
          ["tomatoes", "cutlets", "a bun", "coffee"],
          ["juice", "chiсken", "potatoes", "a bun"],
          ["tea", "Squash", "sausage", "tomatoes"],
          ["vegetables", "Spinach", "fruit", "fish"],
          ["salad", "butter", "Nut", "cutlets"],
          ["a sandwich", "soup", "milk", "pepper"],
          ["Squash", "cheese", "chiсken", "juice"],
          ["fruit", "tomatoes", "salad", "sausage"],
          ["butter", "Spinach", "Turnip", "Nut"],
          ["cutlets", "fish", "Squash", "chiсken"],
          ["pepper", "cheese", "a sandwich", "Turnip"],
          ["sausage", "soup", "butter", "Nut"],
        ],
        answers: [
          "a sandwich",
          "toast",
          "a cake",
          "a bun",
          "tea",
          "coffee",
          "sugar",
          "porridge",
          "cheese",
          "sausage",
          "salt",
          "pepper",
          "salad",
          "soup",
          "meat",
          "chiсken",
          "fish",
          "cutlets",
          "potatoes",
          "tomatoes",
          "vegetables",
          "butter",
          "milk",
          "juice",
          "fruit",
          "Spinach",
          "Squash",
          "Turnip",
          "Nut",
        ],
        id: uuidv4(),
      },
      {
        topic: "Sports in English",
        questions: [
          "чемпион",
          "соревнование",
          "игра",
          "турнир",
          "команда",
          "результат",
          "победа",
          "поражение",
          "ничья",
          "рекорд",
          "медаль",
          "поле",
          "сетка",
          "футбол",
          "баскетбол",
          "волейбол",
          "бокс",
          "гольф",
          "игрок",
          "судья",
          "финт",
          "свисток",
          "шах",
          "мат",
          "сдаться",
          "лунка",
          "берди",
          "шенк",
          "патт",
        ],
        options: [
          ["champion", "game", "championship", "defeat"],
          ["record", "championship", "team", "tournament"],
          ["result", "victory", "game", "hole"],
          ["medal", "field", "net", "tournament"],
          ["team", "football", "basketball", "volleyball"],
          ["boxing", "result", "golf", "player"],
          ["referee", "dummy", "victory", "whistle"],
          ["check", "checkmate", "give up", "defeat"],
          ["draw", "hole", "Birdie", "Shank"],
          ["Putt", "record", "draw", "dummy"],
          ["draw", "dummy", "medal", "Shank"],
          ["tournament", "Birdie", "referee", "field"],
          ["net", "champion", "game", "football"],
          ["basketball", "football", "boxing", "result"],
          ["Putt", "Birdie", "basketball", "record"],
          ["championship", "referee", "field", "volleyball"],
          ["boxing", "dummy", "medal", "whistle"],
          ["checkmate", "golf", "Putt", "victory"],
          ["net", "team", "player", "football"],
          ["defeat", "Putt", "give up", "referee"],
          ["dummy", "champion", "tournament", "team"],
          ["champion", "whistle", "victory", "championship"],
          ["player", "draw", "check", "golf"],
          ["boxing", "tournament", "medal", "checkmate"],
          ["give up", "championship", "game", "volleyball"],
          ["hole", "dummy", "give up", "defeat"],
          ["result", "Birdie", "boxing", "medal"],
          ["golf", "team", "game", "Shank"],
          ["Putt", "player", "draw", "result"],
        ],
        answers: [
          "champion",
          "championship",
          "game",
          "tournament",
          "team",
          "result",
          "victory",
          "defeat",
          "draw",
          "record",
          "medal",
          "field",
          "net",
          "football",
          "basketball",
          "volleyball",
          "boxing",
          "golf",
          "player",
          "referee",
          "dummy",
          "whistle",
          "check",
          "checkmate",
          "give up",
          "hole",
          "Birdie",
          "Shank",
          "Putt",
        ],
        id: uuidv4(),
      },
      {
        topic: "Colors in English",
        questions: [
          "красный",
          "серый",
          "голубой ",
          "синий",
          "зеленый",
          "желтый",
          "розовый",
          "оранжевый",
          "коричневый",
          "черный",
          "белый",
          "фиолетовый",
          "золотой",
          "серебряный",
          "янтарный",
          "голубой",
          "бежевый",
          "телесный цвет",
          "бронзовый",
          "шоколадный",
          "коралловый",
          "джинсовый",
          "сиреневый",
          "жемчужный",
          "малиновый",
          "песочный",
          "белоснежный",
          "бордовый",
        ],
        options: [
          ["Red", "Darkblue", "Grey", "Brown"],
          ["White", "Grey", "Pink", "Amber"],
          ["Red", "Azure", "Lightblue", "Pearl"],
          ["Gold", "Yellow", "Raspberry", "Darkblue"],
          ["Green", "Orange", "Brown", "Lilac"],
          ["Black", "Yellow", "White", "Bodycolour"],
          ["Snow", "Sand", "Pink", "Vinous"],
          ["Beige", "Chocolate", "Violet", "Orange"],
          ["Brown", "Coral", "Red", "Pearl"],
          ["Chocolate", "White", "Vinous", "Yellow"],
          ["Darkblue", "Lightblue", "Black", "Beige"],
          ["Snow", "Pink", "Vinous", "Violet"],
          ["Gold", "Sand", "Grey", "Lilac"],
          ["Azure", "Silver", "Raspberry", "Orange"],
          ["Coral", "White", "Amber", "Vinous"],
          ["Darkblue", "Bronze", "Denimblue", "Azure"],
          ["Beige", "Coral", "Pearl", "Orange"],
          ["Red", "Bodycolour", "Gold", "Lilac"],
          ["Lightblue", "Raspberry", "Bronze", "Amber"],
          ["Sand", "Bodycolour", "Green", "Chocolate"],
          ["Coral", "Silver", "Gold", "Brown"],
          ["Snow", "Denimblue", "Black", "Amber"],
          ["Pearl", "Pink", "Lilac", "Sand"],
          ["Azure", "Grey", "Lightblue", "Pearl"],
          ["Raspberry", "Chocolate", "Red", "Bodycolour"],
          ["Orange", "Sand", "Silver", "Denimblue"],
          ["Chocolate", "Green", "Snow", "Azure"],
          ["Pink", "Grey", "Black", "Vinous"],
        ],
        answers: [
          "Red",
          "Grey",
          "Lightblue",
          "Darkblue",
          "Green",
          "Yellow",
          "Pink",
          "Orange",
          "Brown",
          "White",
          "Black",
          "Violet",
          "Gold",
          "Silver",
          "Amber",
          "Azure",
          "Beige",
          "Bodycolour",
          "Bronze",
          "Chocolate",
          "Coral",
          "Denimblue",
          "Lilac",
          "Pearl",
          "Raspberry",
          "Sand",
          "Snow",
          "Vinous",
        ],
        id: uuidv4(),
      },
      {
        topic: "Jobs in English",
        questions: [
          "Инженер",
          "Спортсмен",
          "Повар ",
          "Полицейский",
          "Продавец",
          "Пожарный",
          "Почтальон",
          "Ветеринар",
          "Художник",
          "Писатель",
          "Музыкант",
          "Актриса",
          "Визажист",
          "Дизайнер",
          "Диджей",
          "Звукорежиссер",
          "Битмейкер",
          "Режиссер",
          "Оператор",
          "Композитор ",
          "Модель ",
          "Переводчик ",
          "Продюсер ",
          "Стилист",
          "Фотограф",
          "Ювелир",
          "Редактор",
          "Сценарист ",
        ],
        options: [
          ["Engineer", "Artist", "Sportsman", "Policeman"],
          ["Writer", "Sportsman", "Veterinarian", "Musician"],
          ["Actress", "Makeup artist", "Cook", "Designer"],
          ["DJ", "Sound Producer", "Beatmaker", "Policeman"],
          ["Seller", "Director", "Cameraman", "Composer"],
          ["Model", "Fireman", "Photographer", "Jeweller"],
          ["Editor", "Screenwriter", "Postman", "Musician"],
          ["Engineer", "Sportsman", "Cook", "Veterinarian"],
          ["Artist", "Policeman", "Designer", "Makeup artist"],
          ["Model", "Writer", "DJ", "Fireman"],
          ["Sound Producer", "Photographer", "Musician", "Cameraman"],
          ["Beatmaker", "Sportsman", "Jeweller", "Actress"],
          ["Makeup artist", "Composer", "Stylist", "Director"],
          ["Editor", "Designer", "Sound Producer", "Actress"],
          ["Policeman", "Engineer", "DJ", "Postman"],
          ["Interpreter", "Jeweller", "Screenwriter", "Sound Producer"],
          ["Beatmaker", "Sportsman", "Writer", "Makeup artist"],
          ["Model", "Director", "Producer", "Composer"],
          ["Designer", "Photographer", "Cameraman", "Screenwriter"],
          ["Jeweller", "Fireman", "Beatmaker", "Composer"],
          ["Model", "Stylist", "Veterinarian", "DJ"],
          ["Editor", "Interpreter", "Postman", "Cook"],
          ["Composer", "Sound Producer", "Producer", "Designer"],
          ["Writer", "Interpreter", "DJ", "Stylist"],
          ["Photographer", "Veterinarian", "Director", "Artist"],
          ["Sound Producer", "Jeweller", "Cook", "Artist"],
          ["Designer", "Interpreter", "Editor", "Writer"],
          ["Stylist", "Postman", "Composer", "Screenwriter"],
        ],
        answers: [
          "Engineer",
          "Sportsman",
          "Cook",
          "Policeman",
          "Seller",
          "Fireman",
          "Postman",
          "Veterinarian",
          "Artist",
          "Writer",
          "Musician",
          "Actress",
          "Makeup artist",
          "Designer",
          "DJ",
          "Sound Producer",
          "Beatmaker",
          "Director",
          "Cameraman",
          "Composer",
          "Model",
          "Interpreter",
          "Producer",
          "Stylist",
          "Photographer",
          "Jeweller",
          "Editor",
          "Screenwriter",
        ],
        id: uuidv4(),
      },
      {
        topic: "Emotions in English",
        questions: [
          "злой",
          "раздраженный",
          "скучающий",
          "спокойный",
          "заботливый",
          "недоумевающий",
          "уверенный",
          "опасный",
          "подавленный",
          "расстроенный",
          "отстраненный",
          "мечтательный",
          "опустошенный",
          "энергичный",
          "взволнованный",
          "счастливый ",
          "голодный ",
          "враждебный",
          "заинтересованный",
          "изолированный",
          "радостный",
          "прекрасный",
          "везучий",
          "безумный",
          "умиротворенный",
          "оптимистично-настроенный",
          "довольный",
          "лишенный сил",
        ],
        options: [
          ["Angry", "Careful", "Annoyed", "Bored"],
          ["Calm", "Annoyed", "Confused", "Confident"],
          ["Dangerous", "Depressed", "Bored", "Disappointed"],
          ["Distant", "Dreamy", "Empty", "Calm"],
          ["Careful", "Energetic", "Excited", "Happy"],
          ["Hungry", "Confused", "Hostile", "Interested"],
          ["Isolated", "Joyful", "Confident", "Lovely"],
          ["Lucky", "Mad", "Peaceful", "Dangerous"],
          ["Depressed", "Optimistic", "Hostile", "Excited"],
          ["Angry", "Disappointed", "Pleased", "Powerless"],
          ["Careful", "Annoyed", "Distant", "Bored"],
          ["Calm", "Joyful", "Energetic", "Dreamy"],
          ["Empty", "Happy", "Lucky", "Mad"],
          ["Optimistic", "Energetic", "Powerless", "Interested"],
          ["Depressed", "Empty", "Excited", "Joyful"],
          ["Bored", "Distant", "Peaceful", "Happy"],
          ["Hungry", "Interested", "Calm", "Disappointed"],
          ["Careful", "Hostile", "Pleased", "Dreamy"],
          ["Optimistic", "Annoyed", "Interested", "Angry"],
          ["Confused", "Depressed", "Peaceful", "Isolated"],
          ["Joyful", "Isolated", "Confident", "Pleased"],
          ["Hungry", "Lovely", "Empty", "Hostile"],
          ["Happy", "Distant", "Lucky", "Confident"],
          ["Calm", "Disappointed", "Dreamy", "Mad"],
          ["Peaceful", "Annoyed", "Angry", "Joyful"],
          ["Interested", "Optimistic", "Confused", "Hungry"],
          ["Careful", "Empty", "Pleased", "Hostile"],
          ["Distant", "Joyful", "Disappointed", "Powerless"],
        ],
        answers: [
          "Angry",
          "Annoyed",
          "Bored",
          "Calm",
          "Careful",
          "Confused",
          "Confident",
          "Dangerous",
          "Depressed",
          "Disappointed",
          "Distant",
          "Dreamy",
          "Empty",
          "Energetic",
          "Excited",
          "Happy",
          "Hungry",
          "Hostile",
          "Interested",
          "Isolated",
          "Joyful",
          "Lovely",
          "Lucky",
          "Mad",
          "Peaceful",
          "Optimistic",
          "Pleased",
          "Powerless",
        ],
        id: uuidv4(),
      },
    ],
    grammarTopic: {
      title: "Present Simple",
      id: uuidv4(),
      icon: "",
      route: "/grammar-list",
    },
    grammarTopics: [
      {
        title: "Present Simple",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },
      {
        title: "Present Perfect",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },
      {
        title: "Present Continious",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },
      {
        title: "Past Simple",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },

      {
        title: "Past Perfect",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },
      {
        title: "Past Continious",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },
      {
        title: "Infinitive & Gerund",
        id: uuidv4(),
        icon: "",
        route: "/grammar-list",
      },
    ],
  },
  getters: {
    getGame(state) {
      return state.game;
    },
    getLevel(state) {
      return state.level;
    },
    getVocabularyTopic(state) {
      return state.vocabularyTopic;
    },
    getTestTopic(state) {
      return state.testTopic;
    },
    getGrammarTopic(state) {
      return state.grammarTopic;
    },
  },
  mutations: {
    updateGame(state, newGame) {
      localStorage.setItem("game", JSON.stringify(newGame));
      state.game = newGame;
    },
    updateLevel(state, newLevel) {
      localStorage.setItem("level", newLevel);
      state.level = newLevel;
    },
    updateLoader(state, payload) {
      state.loader = payload;
    },
    updatePageLoader(state, payload) {
      state.pageLoader = payload;
    },
    updateVocabularyTopic(state, topic) {
      state.vocabularyTopic = topic;
    },
    updateTestTopic(state, topic) {
      state.testTopic = topic;
    },
    updateGrammarTopic(state, topic) {
      state.grammarTopic = topic;
    },
    updateTheme(state, theme) {
      state.theme.isDark = theme;
    },
  },
  actions: {
    callGameUpdation({ commit }, newGame) {
      commit("updateGame", newGame);
    },
    callLevelUpdation({ commit }, newLevel) {
      commit("updateLevel", newLevel);
    },
    callLoaderUpdation({ commit }, payload) {
      commit("updateLoader", payload);
    },
    callPageLoaderUpdation({ commit }, payload) {
      commit("updatePageLoader", payload);
    },
    callVocabularyTopicUpdation({ commit }, topic) {
      commit("updateVocabularyTopic", topic);
    },
    callTestTopicUpdation({ commit }, topic) {
      commit("updateTestTopic", topic);
    },
    callGrammarTopicUpdation({ commit }, topic) {
      commit("updateGrammarTopic", topic);
    },
    callThemeUpdation({ commit }, theme) {
      localStorage.setItem("isDark", JSON.stringify(theme));
      commit("updateTheme", theme);
    },
  },
  modules: {},
});
